# https://nexte.st/book/configuration.html

[test-groups.serial-integration]
# Run integration tests serially.
# We only apply this setting in the `ci` profile; the CI builders are small
# enough that running multiple integration tests at the same time actually
# makes the entire test suite complete slower.
max-threads = 1

[[profile.default.overrides]]
# `kind(test)` means integration tests in the `../tests/` directory.
# https://nexte.st/book/filter-expressions.html#basic-predicates
# List tests that match a filter with `cargo nextest list -E 'some-filter-expr'`
filter = 'package(home-mangler) and kind(test)'
test-group = 'serial-integration'

[profile.ci]
# Print out output for failing tests as soon as they fail, and also at the end
# of the run (for easy scrollability).
failure-output = "immediate-final"
# Do not cancel the test run on the first failure.
fail-fast = false
